ANALYSISFILE=./mdanalysis.py

nmol=400
e0=6e-4

CURRENTFOLDER=$(pwd)
TOTALFOLDER=$CURRENTFOLDER/"$nmol"/E0_"$e0"
XYZFOLDER=$TOTALFOLDER/xyznve
python $ANALYSISFILE $XYZFOLDER

PACFOLDER=$TOTALFOLDER/pac
COORDFOLDER=$TOTALFOLDER/coord
mkdir $PACFOLDER
mkdir $COORDFOLDER
sleep 3s

mv $XYZFOLDER/simu_*.xc.xyz.pac.txt $PACFOLDER
mv $XYZFOLDER/simu_*.xc.xyz.scoord.txt $COORDFOLDER

sleep 10s

XYZFOLDER=$TOTALFOLDER/noneqxyznve
python $ANALYSISFILE $XYZFOLDER

PACFOLDER=$TOTALFOLDER/noneqpac
COORDFOLDER=$TOTALFOLDER/noneqcoord
mkdir $PACFOLDER
mkdir $COORDFOLDER
sleep 3s

mv $XYZFOLDER/simu_*.xc.xyz.pac.txt $PACFOLDER
mv $XYZFOLDER/simu_*.xc.xyz.scoord.txt $COORDFOLDER
